/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobasededatos;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NicoPlaceres
 */
public class AgregarDuenioMascota extends javax.swing.JFrame {
    
    private Personas pers = null;
    private Mascota masc = null;
    private Veterinario veto = null;
    private Veterinaria veta= null;
    
    

    /**
     * Creates new form AgregarDuenioMascota
     */
    public AgregarDuenioMascota( Personas persona , Veterinario veto , Veterinaria veta) {
        this.pers = persona;
        this.veta = veta;
        this.veto=veto;
        initComponents();
        this.setResizable(false);
        ArrayList<String> tipos_mascs;
        try {
            tipos_mascs = DB_Driver.obtenerTiposMascotas();
            for (String tipo_masc : tipos_mascs) {
            t_masc.addItem(tipo_masc);
        }
        } catch (SQLException ex) {
            Logger.getLogger(AgregarDuenioMascota.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private AgregarDuenioMascota() {
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        JTextDuenioCI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextMascotaNombre = new javax.swing.JTextField();
        JTextMascotaPeso = new javax.swing.JTextField();
        JTextNumeroChip = new javax.swing.JTextField();
        JTextMascotaEdad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JBottonGuardarMascDuen = new javax.swing.JButton();
        t_masc = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        raza_masc = new javax.swing.JComboBox<>();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Telugu Sangam MN", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Dueño y/o Mascota ");

        JTextDuenioCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextDuenioCIActionPerformed(evt);
            }
        });

        jLabel2.setText("DATOS DEL DUEÑO:");

        jLabel4.setText("CI Persona *");

        JTextMascotaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextMascotaNombreActionPerformed(evt);
            }
        });

        JTextMascotaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextMascotaPesoActionPerformed(evt);
            }
        });

        JTextNumeroChip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNumeroChipActionPerformed(evt);
            }
        });

        JTextMascotaEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextMascotaEdadActionPerformed(evt);
            }
        });

        jLabel9.setText("DATOS DEL MASCOTA:");

        jLabel10.setText("Numero CHIP*");

        jLabel11.setText("Nombre*");

        jLabel12.setText("Peso*");

        jLabel14.setText("Fecha nacimiento*");

        JBottonGuardarMascDuen.setText("Guardar");
        JBottonGuardarMascDuen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBottonGuardarMascDuenActionPerformed(evt);
            }
        });

        t_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_mascActionPerformed(evt);
            }
        });

        jLabel15.setText("Tipo Mascota");

        jLabel16.setText("Raza");

        raza_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raza_mascActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextDuenioCI, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTextMascotaNombre)
                                            .addComponent(JTextNumeroChip)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(JTextMascotaPeso))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t_masc, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JTextMascotaEdad)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(JBottonGuardarMascDuen)
                                                .addGap(89, 89, 89))
                                            .addComponent(raza_masc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTextDuenioCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTextNumeroChip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTextMascotaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTextMascotaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JTextMascotaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(18, 18, 18)
                        .addComponent(t_masc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(raza_masc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBottonGuardarMascDuen)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextDuenioCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextDuenioCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextDuenioCIActionPerformed

    private void JTextMascotaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextMascotaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextMascotaNombreActionPerformed

    private void JTextMascotaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextMascotaPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextMascotaPesoActionPerformed

    private void JTextNumeroChipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNumeroChipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNumeroChipActionPerformed

    private void JTextMascotaEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextMascotaEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextMascotaEdadActionPerformed

    private void JBottonGuardarMascDuenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBottonGuardarMascDuenActionPerformed
        // Se crea el dueno y la mascota. se obtienen los datos del dueno y de la mascota. 
        //Datos del dueno
        String ci = JTextDuenioCI.getText();
        pers = new Personas(ci);
       
      
        
        //Datos de la Mascota
        String num_chip = JTextNumeroChip.getText();
        String nombreMascota = JTextMascotaNombre.getText();
        int pesoMascota=Integer.parseInt(JTextMascotaPeso.getText());
        String fechaNac = JTextMascotaEdad.getText();
        
         masc = new Mascota(num_chip,nombreMascota,pesoMascota, fechaNac);
         masc.setTipo(this.t_masc.getSelectedItem().toString());
         masc.setRaza(this.raza_masc.getSelectedItem().toString());
        try {
            boolean bandera = DB_Driver.emptyDuenio(pers, masc,veto,veta);
            
            if(bandera == true){
                System.out.println("succes");
                JOptionPane.showMessageDialog(null, "Mascota creada correctamente.");
                this.dispose();
                 //JOptionPane.showMessageDialog(null,"Mensaje de Error","Mensaje de Error", JOptionPane.); //Tipo de mensaje   
            }
            else{
                JFrameAddPersona open = new JFrameAddPersona(pers, masc,veto,veta);
                open.setVisible(true);
                 open.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
        }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AgregarDuenioMascota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AgregarDuenioMascota.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_JBottonGuardarMascDuenActionPerformed

    private void raza_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raza_mascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raza_mascActionPerformed

    private void t_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_mascActionPerformed
        // TODO add your handling code here:
        this.raza_masc.removeAllItems();
        String tipo = t_masc.getSelectedItem().toString();
        ArrayList<String> razas_mascs;
        try {
            razas_mascs = DB_Driver.obtenerRazasDeTipo(tipo);
            for (String raza_masc : razas_mascs) {
                this.raza_masc.addItem(raza_masc);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AgregarDuenioMascota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_mascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDuenioMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDuenioMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDuenioMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDuenioMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDuenioMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBottonGuardarMascDuen;
    private javax.swing.JTextField JTextDuenioCI;
    private javax.swing.JTextField JTextMascotaEdad;
    private javax.swing.JTextField JTextMascotaNombre;
    private javax.swing.JTextField JTextMascotaPeso;
    private javax.swing.JTextField JTextNumeroChip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> raza_masc;
    private javax.swing.JComboBox<String> t_masc;
    // End of variables declaration//GEN-END:variables
}
